// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	sellers "gameprice-api/business/sellers"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: seller, id
func (_m *Repository) Delete(seller *sellers.Domain, id int) (string, error) {
	ret := _m.Called(seller, id)

	var r0 string
	if rf, ok := ret.Get(0).(func(*sellers.Domain, int) string); ok {
		r0 = rf(seller, id)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*sellers.Domain, int) error); ok {
		r1 = rf(seller, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields:
func (_m *Repository) FindAll() ([]sellers.Domain, error) {
	ret := _m.Called()

	var r0 []sellers.Domain
	if rf, ok := ret.Get(0).(func() []sellers.Domain); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sellers.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: id
func (_m *Repository) FindByID(id int) (*sellers.Domain, error) {
	ret := _m.Called(id)

	var r0 *sellers.Domain
	if rf, ok := ret.Get(0).(func(int) *sellers.Domain); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sellers.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: seller
func (_m *Repository) Insert(seller *sellers.Domain) (*sellers.Domain, error) {
	ret := _m.Called(seller)

	var r0 *sellers.Domain
	if rf, ok := ret.Get(0).(func(*sellers.Domain) *sellers.Domain); ok {
		r0 = rf(seller)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sellers.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*sellers.Domain) error); ok {
		r1 = rf(seller)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: seller, id
func (_m *Repository) Update(seller *sellers.Domain, id int) (*sellers.Domain, error) {
	ret := _m.Called(seller, id)

	var r0 *sellers.Domain
	if rf, ok := ret.Get(0).(func(*sellers.Domain, int) *sellers.Domain); ok {
		r0 = rf(seller, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sellers.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*sellers.Domain, int) error); ok {
		r1 = rf(seller, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
