// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	wishes "gameprice-api/business/wishes"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: wish, id
func (_m *Repository) Delete(wish *wishes.Domain, id int) (string, error) {
	ret := _m.Called(wish, id)

	var r0 string
	if rf, ok := ret.Get(0).(func(*wishes.Domain, int) string); ok {
		r0 = rf(wish, id)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*wishes.Domain, int) error); ok {
		r1 = rf(wish, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields:
func (_m *Repository) FindAll() ([]wishes.Domain, error) {
	ret := _m.Called()

	var r0 []wishes.Domain
	if rf, ok := ret.Get(0).(func() []wishes.Domain); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]wishes.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: id
func (_m *Repository) FindByID(id int) (*wishes.Domain, error) {
	ret := _m.Called(id)

	var r0 *wishes.Domain
	if rf, ok := ret.Get(0).(func(int) *wishes.Domain); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*wishes.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: wish
func (_m *Repository) Insert(wish *wishes.Domain) (*wishes.Domain, error) {
	ret := _m.Called(wish)

	var r0 *wishes.Domain
	if rf, ok := ret.Get(0).(func(*wishes.Domain) *wishes.Domain); ok {
		r0 = rf(wish)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*wishes.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*wishes.Domain) error); ok {
		r1 = rf(wish)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: wish, id
func (_m *Repository) Update(wish *wishes.Domain, id int) (*wishes.Domain, error) {
	ret := _m.Called(wish, id)

	var r0 *wishes.Domain
	if rf, ok := ret.Get(0).(func(*wishes.Domain, int) *wishes.Domain); ok {
		r0 = rf(wish, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*wishes.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*wishes.Domain, int) error); ok {
		r1 = rf(wish, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
