// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	steamapis "gameprice-api/business/steamapis"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetData provides a mock function with given fields: appid
func (_m *Repository) GetData(appid string) (steamapis.Domain, error) {
	ret := _m.Called(appid)

	var r0 steamapis.Domain
	if rf, ok := ret.Get(0).(func(string) steamapis.Domain); ok {
		r0 = rf(appid)
	} else {
		r0 = ret.Get(0).(steamapis.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(appid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetID provides a mock function with given fields: name
func (_m *Repository) GetID(name string) (steamapis.Domain, error) {
	ret := _m.Called(name)

	var r0 steamapis.Domain
	if rf, ok := ret.Get(0).(func(string) steamapis.Domain); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(steamapis.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
