name: on-push-master

on:
    pull_request:
        branches:
            - "master"
    push:
        branches:
            - "master"
            - "feature-*"
            - "hotfix-*"
            - "bug-*"

jobs:
    api-test:
        name: api test - run unitest on action
        runs-on: ubuntu-latest
        container: golang:1.17
        services:
            mysql:
                image: mariadb:10.1
                env:
                    MYSQL_ROOT_PASSWORD: password
                ports:
                    - 3306:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        strategy:
            matrix:
                go: ["1.17"]
        steps:
            - name: "Git Checkout"
              uses: actions/checkout@v2
            - name: create database
              run: |
                  apt-get update
                  apt-get install -y mariadb-client
                  mysql --host mysql -uroot -ppassword -e "CREATE DATABASE IF NOT EXISTS gameprice"
            - name: running unitest
              run: |
                  echo "${{ secrets.ENV }}" > ./app/config/config.json
                  # mv ./app/config/example-config.json ./app/config/config.json
                  go mod tidy
                  go test ./... -cover -failfast

    deploy-heroku:
        name: deploy
        runs-on: ubuntu-latest
        needs: api-test
        steps:
            - uses: actions/checkout@v2
            - uses: akhileshns/heroku-deploy@v3.12.12
              with:
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: "gameprice-api2"
                  heroku_email: "waldofelix1@gmail.com"
                  usedocker: true
